# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on an OS X system.
stages:
  - build
  - archive

build_project:
  stage: build
  script:
    - xcodebuild clean -project xID3.xcodeproj -scheme xID3 | xcpretty
    - xcodebuild test -project xID3.xcodeproj -scheme xID3 -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.2' | xcpretty -s
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath build/xID3 -scheme xID3
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/xID3.xcarchive" -exportPath "build/xID3.ipa" -exportProvisioningProfile "ProvisioningProfileName"
  only:
    - master
  artifacts:
    paths:
    - build/xID3.ipa
  tags:
    - ios_9-2
    - xcode_7-2
    - osx_10-11
