language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="xID3.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="xID3"
  - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"     SCHEME="$IOS_FRAMEWORK_SCHEME"    SDK="$IOS_SDK"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild -project "$PROJECT" -list

  # Build Framework in Release
  - xcodebuild -project "$PROJECT" -target "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build  | xcpretty
